import re

DEFAULT_PROFILE_ID = "cube"
SETTINGS_FILE_VERSION = 2
DISCORD_RPC_DEFAULT_CLIENT_ID = "1470109631333404742"

ENV_SOUND = "CUBEPET_SOUND"
ENV_DEBUG = "CUBEPET_DEBUG"
ENV_HORROR_GAME = "CUBEPET_HORROR_GAME"
ENV_STEAL_FOCUS = "CUBEPET_STEAL_FOCUS"
ENV_RESPECT_INPUT = "CUBEPET_RESPECT_INPUT"
ENV_ACTIVE_GRACE_S = "CUBEPET_ACTIVE_GRACE_S"
ENV_NOTIFICATIONS = "CUBEPET_NOTIFICATIONS"
ENV_DISCORD_RPC = "CUBEPET_DISCORD_RPC"
ENV_DISCORD_RPC_CLIENT_ID = "CUBEPET_DISCORD_RPC_CLIENT_ID"
ENV_IMAGE_IDLE_S = "CUBEPET_IMAGE_IDLE_S"
ENV_IMAGE_MIN_S = "CUBEPET_IMAGE_MIN_S"
ENV_IMAGE_MAX_S = "CUBEPET_IMAGE_MAX_S"
ENV_PROFILE = "CUBEPET_PROFILE"
ENV_SELECT_PET = "CUBEPET_SELECT_PET"
ENV_HUNGER = "CUBEPET_HUNGER"
ENV_HUNGER_FULL_S = "CUBEPET_HUNGER_FULL_S"
ENV_EDITOR_MISCHIEF = "CUBEPET_EDITOR_MISCHIEF"
ENV_IMAGE_HEIST = "CUBEPET_IMAGE_HEIST"
ENV_EDITOR_HEIST = "CUBEPET_EDITOR_HEIST"
ENV_CLONES = "CUBEPET_CLONES"
ENV_CURSOR_GAMES = "CUBEPET_CURSOR_GAMES"
ENV_MOUSE_LOCK = "CUBEPET_MOUSE_LOCK"
ENV_WINDOW_KILL = "CUBEPET_WINDOW_KILL"

DEFAULT_ACTIVE_GRACE_S = 2.0
# Require a meaningful idle gap before the pet starts disruptive actions.
DEFAULT_IMAGE_IDLE_S = 2.0
MIN_IMAGE_HEIST_START_S = 2.0
# Less frequent by default; can be tuned via environment variables.
# Slightly more frequent by default (still gated by idle checks).
DEFAULT_IMAGE_MIN_S = 18.0
DEFAULT_IMAGE_MAX_S = 45.0

# Editor heist timing (seconds). This is the "Notepad window" prank.
DEFAULT_EDITOR_HEIST_MIN_S = 18.0
DEFAULT_EDITOR_HEIST_MAX_S = 45.0
DEFAULT_EDITOR_HEIST_RETRY_MIN_S = 12.0
DEFAULT_EDITOR_HEIST_RETRY_MAX_S = 28.0

# Window kill (tab/window close) timing (seconds).
DEFAULT_WINDOW_KILL_MIN_S = 70.0
DEFAULT_WINDOW_KILL_MAX_S = 190.0
DEFAULT_WINDOW_KILL_SUCCESS_MIN_S = 95.0
DEFAULT_WINDOW_KILL_SUCCESS_MAX_S = 240.0
DEFAULT_WINDOW_KILL_RETRY_MIN_S = 35.0
DEFAULT_WINDOW_KILL_RETRY_MAX_S = 110.0
DEFAULT_WINDOW_KILL_TRIGGER_CHANCE = 0.11
DEFAULT_HUNGER_FULL_S = 900.0
MIN_HUNGER_FULL_S = 30.0

ENV_TRUE_VALUES = {"1", "true", "TRUE", "yes", "YES", "on", "ON"}
ENV_FALSE_VALUES = {"0", "false", "FALSE", "no", "NO", "off", "OFF"}

TOKEN_RE = re.compile(r"[A-Za-z0-9_]{2,}")
IMAGE_EXTS_WITH_PIL = frozenset({".png", ".jpg", ".jpeg", ".gif", ".bmp", ".webp", ".ppm", ".pgm"})
IMAGE_EXTS_TK_ONLY = frozenset({".png", ".gif", ".ppm", ".pgm"})
